apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gomux1
  namespace: argocd
spec:
  destination:
    namespace: gomux1
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/rakhbari/gomux1-config.git
    path: helm/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
